version: "3.8"

services:
  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=veterinaria
      - MONGO_USERNAME=will
      - MONGO_PASSWORD=will
    ports:
      - 27017:27017
    volumes:
      - ./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-data:/data/db
    command: mongod
volumes:
  mongo-data: